chore: Change authorship reposense
AY2324S2-CS2113T-T09-1/tp pull request #144
Opened 2024-04-05 06:54 UTC by wenenhoe

# Checklist for feature implementation and modification
Closes #143
- [x] Added relevant milestone (under milestone tab on the right)

2024-04-05 14:01 UTC, nickczh requested changes
Thanks Wen En for the effort to change the authorship repo-sense!

https://nus-cs2113-ay2324s2.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking

In the link above, the indication is usually:
`//@@author johndoe`
without a space after the backslash.

Not sure if that is necessary, but for your consideration. Additionally, an empty author tag is only when you don't know who wrote the code segment below. Some empty author tags already don't have more code below them, so may not be necessary?

2024-04-05 16:08 UTC, wenenhoe commented
According to the [RepoSense docs](https://reposense.org/ug/usingAuthorTags.html), it is part of the supported comment formats. Additionally, the docs also mention that the empty author tag is used to denote the end of a code segment written by the author.

2024-04-05 16:09 UTC, wenenhoe commented on src/main/java/meditracker/command/AddCommand.java
> +// @@author nickczh
Good catch! Resolved in 82b084f

2024-04-05 16:18 UTC, T0nyLin approved these changes
Thank you for the changes in authorship!

2024-04-05 16:27 UTC, kyuichyi approved these changes
LGTM! Thanks for the changes!

2024-04-06 01:37 UTC, nickczh approved these changes
LGTM! Thank you for the changes.

2024-04-06 01:39 UTC, merged